version: "3.9"

services:
  miner:
    image: rdavidoff/twitch-channel-points-miner-v2
    # Actual github at: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    labels:
      - traefik.enable=true
      - traefik.http.routers.miner.entrypoints=websecure
      - traefik.http.routers.miner.rule=Host(`miner.christianfds.dev`)
      - traefik.http.routers.miner.tls.certresolver=letsencryptresolver
      - traefik.http.services.miner.loadbalancer.server.port=5000
      - traefik.http.routers.miner.middlewares=miner-auth
      - traefik.http.middlewares.miner-auth.basicauth.usersfile=/users/users.u
    volumes:
      - /data/container/twitch-miner/analytics:/usr/src/app/analytics
      - /data/container/twitch-miner/cookies:/usr/src/app/cookies
      - /data/container/twitch-miner/logs:/usr/src/app/logs
      - /data/container/twitch-miner/run.py:/usr/src/app/run.py:ro
      - /data/container/traefik/users.u:/users/users.u
    ports:
      - target: 5000
        published: 5000
        mode: host
    networks:
      - traefik

networks:
  traefik:
    external: true        
