version: "3.9"

services:
  miner:
    image: rdavidoff/twitch-channel-points-miner-v2
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=Host(`miner.christianfds.dev`)
      - traefik.http.routers.portainer.tls.certresolver=leresolver
      - traefik.http.services.portainer.loadbalancer.server.port=5000
    volumes:
      - /data/container/twitch-miner/analytics:/usr/src/app/analytics
      - /data/container/twitch-miner/cookies:/usr/src/app/cookies
      - /data/container/twitch-miner/logs:/usr/src/app/logs
      - /data/container/twitch-miner/run.py:/usr/src/app/run.py:ro
    ports:
      - "5000:5000"
